version: '3'
services:
  madeira-faq:
    image: madeira-faq:latest
    build: .
    container_name: "madeira-faq"
    environment:
      - TZ=America/Sao_Paulo
      - DEBUG=1
      - COMPOSER_INSTAL=1
      - COMPOSER_INSTALL_PARANS="--prefer-dist"
    restart: always
    working_dir: /var/www/default
    ports:
      - "8080:80"
      - "8081:443"
    volumes:
      - ./:/var/www/default
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql:8.0.18
    container_name: "madeira-faq-mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=madeira-faq
    ports:
      - 3307:3306
