-- MySQL Script generated by MySQL Workbench
-- ter 17 dez 2019 09:18:03 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema madeira_faq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema madeira_faq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `madeira_faq` ;
USE `madeira_faq` ;

-- -----------------------------------------------------
-- Table `madeira_faq`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madeira_faq`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `title_slug` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `FUILLTEXT` (`title`) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Categorização das perguntas';


-- -----------------------------------------------------
-- Table `madeira_faq`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `madeira_faq`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tags_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `title_slug` VARCHAR(255) NOT NULL,
  `answer` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `updated_at` DATETIME NOT NULL DEFAULT current_timestamp,
  `enabled` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX `FULLTEXT` (`title`, `answer`) VISIBLE,
  INDEX `fk_questions_tags_idx` (`tags_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_tags`
    FOREIGN KEY (`tags_id`)
    REFERENCES `madeira_faq`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
