<?php /** @var Faq\Entity\Tag $tag */ ?>
<?php /** @var Faq\Entity\Question $question */ ?>


<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <form action="<?= $this->url('faq.question') ?>" method="get">
            <div class="input-group input-group-lg">
                <span class="input-group-addon" id="sizing-addon1">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </span>
                <input name="search" type="text" value="<?= $this->search; ?>" minlength="3" autocomplete="off" autofocus class="form-control" placeholder="Search" aria-label="Search" aria-describedby="sizing-addon1">
            </div>
        </form>
    </div>
</div>

<br>
<br>

<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <?php foreach ($this->tags as $tag): ?>
                <a
                    href="<?= $this->url('faq.question.tag', ['tag' => $tag->title_slug]) ?>"
                    class="list-group-item <?= ($this->selectedTag === $tag->title_slug) ? 'active' : '' ?>"
                ><?= $tag->title; ?></a>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-9">
        <div class="list-group">
            <?php foreach ($this->questions as $question): ?>
                <a href="<?= $this->url('faq.answer', ['tag' => $question->tag->title_slug, 'title' => $question->title_slug]) ?>" class="list-group-item">
                    <h4 class="list-group-item-heading"><?= $question->title?></h4>
                    <p class="list-group-item-text">
                        <h4><small><?= $question->tag->title?></small></h4>
                        <?= substr(strip_tags($question->answer), 0, 100); ?> ...
                    </p>
                </a>
            <?php endforeach; ?>
        </div>
    </div>
</div>