<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js');
?>
<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="/favicon.ico" />
    <?=$this->headTitle('Madeira Madeira')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
</head>
<body>
    <header class="container">
        <div class="page-header">
            <h2>madeira<b>madeira</b> <small>Faq</small></h2>
        </div>
    </header>

    <div>
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer>
        <div class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> by Silvanei Soares Santos.
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>
